### ISSUE TITLE
Have you modified the 1st conv layer to Ghost module?

### ISSUE THREAD

**Issue by iamhankai** [TingsongYu/ghostnet_cifar10#1]
Have you modified the 1st conv layer to Ghost module? We did not touch the 1st conv in our experiments.

https://github.com/iamhankai/ghostnet.pytorch/issues/16

**Comment by TingsongYu** [comment]
之前的实验对第一个卷积层进行了修改，最近也补充了未修改第一个卷积层的实验。两个实验分别在
/results/ghost-vgg-16-not-1st-conv
/results/ghost-resnet-56-not-1st-conv

里面有log，但是acc仍旧未有改善，您有时间的话，帮忙看看log里有哪些参数设置不正确的么，非常感谢！

**Comment by iamhankai** [comment]
There are duplicated BN and ReLU in your code. The learning rate only decay once which is not enough.

**Comment by U-C-J** [comment]
> 之前的实验对第一个卷积层进行了修改，最近也补充了未修改第一个卷积层的实验。两个实验分别在
> /results/ghost-vgg-16-not-1st-conv
> /results/ghost-resnet-56-not-1st-conv
> 
> 里面有log，但是acc仍旧未有改善，您有时间的话，帮忙看看log里有哪些参数设置不正确的么，非常感谢！

Hello did you find out why the parameter is 0.43M?  I also replaced ResNet56 with ghost module and got 0.44M parameters and 66.6M flops. I didn't find out where the 0.01M parameter number difference comes from.
Computational complexity:       66.61 MMac
Number of parameters:           0.44 M

**Comment by U-C-J** [comment]
> Have you modified the 1st conv layer to Ghost module? We did not touch the 1st conv in our experiments.
> 
> [iamhankai/ghostnet.pytorch#16](https://github.com/iamhankai/ghostnet.pytorch/issues/16)

Hello did you use 45k to train or 50k to train for cifar10? If you use 45k, what is your random seed number to split the training samples?

**Comment by DUhaixia** [comment]
Isparallel = True if len(args.gpu) > 1 else False
    if len(args.gpu) > 1:
       Isparallel = True
    else:
       Isparallel = False
gpu设置的时候出现这种问题这个怎么解决
Traceback (most recent call last):
  File "D:/rhnet-daima/ghostnet_cifar10-master/bin/02_main.py", line 47, in <module>
    Isparallel = True if len(args.gpu) > 1 else False
TypeError: object of type 'NoneType' has no len()

**Comment by iamhankai** [comment]
> Isparallel = True if len(args.gpu) > 1 else False if len(args.gpu) > 1: Isparallel = True else: Isparallel = False gpu设置的时候出现这种问题这个怎么解决 Traceback (most recent call last): File "D:/rhnet-daima/ghostnet_cifar10-master/bin/02_main.py", line 47, in Isparallel = True if len(args.gpu) > 1 else False TypeError: object of type 'NoneType' has no len()

看起来你没有设置gpu id？
