### ISSUE TITLE
按照步骤对events.out文件使用tensorboard进行特征图可视化报错

### ISSUE THREAD

**Issue by yyyssq** [TingsongYu/ghostnet_cifar10#11]
Traceback (most recent call last):
  File "bin/04_fmap_vis.py", line 48, in <module>
    model.load_state_dict(state_dict_cpu)
  File "/home/ysq/文档/ghostnet_cifar10-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "features.0.primary_conv.0.weight", "features.0.primary_conv.1.weight", "features.0.primary_conv.1.bias", "features.0.primary_conv.1.running_mean", "features.0.primary_conv.1.running_var", "features.0.cheap_operation.0.weight", "features.0.cheap_operation.1.weight", "features.0.cheap_operation.1.bias", "features.0.cheap_operation.1.running_mean", "features.0.cheap_operation.1.running_var", "features.1.weight", "features.1.bias", "features.1.running_mean", "features.1.running_var", "features.3.primary_conv.0.weight", "features.3.primary_conv.1.weight", "features.3.primary_conv.1.bias", "features.3.primary_conv.1.running_mean", "features.3.primary_conv.1.running_var", "features.3.cheap_operation.0.weight", "features.3.cheap_operation.1.weight", "features.3.cheap_operation.1.bias", "features.3.cheap_operation.1.running_mean", "features.3.cheap_operation.1.running_var", "features.4.weight", "features.4.bias", "features.4.running_mean", "features.4.running_var", "features.7.primary_conv.0.weight", "features.7.primary_conv.1.weight", "features.7.primary_conv.1.bias", "features.7.primary_conv.1.running_mean", "features.7.primary_conv.1.running_var", "features.7.cheap_operation.0.weight", "features.7.cheap_operation.1.weight", "features.7.cheap_operation.1.bias", "features.7.cheap_operation.1.running_mean", "features.7.cheap_operation.1.running_var", "features.8.weight", "features.8.bias", "features.8.running_mean", "features.8.running_var", "features.10.primary_conv.0.weight", "features.10.primary_conv.1.weight", "features.10.primary_conv.1.bias", "features.10.primary_conv.1.running_mean", "features.10.primary_conv.1.running_var", "features.10.cheap_operation.0.weight", "features.10.cheap_operation.1.weight", "features.10.cheap_operation.1.bias", "features.10.cheap_operation.1.running_mean", "features.10.cheap_operation.1.running_var", "features.11.weight", "features.11.bias", "features.11.running_mean", "features.11.running_var", "features.14.primary_conv.0.weight", "features.14.primary_conv.1.weight", "features.14.primary_conv.1.bias", "features.14.primary_conv.1.running_mean", "features.14.primary_conv.1.running_var", "features.14.cheap_operation.0.weight", "features.14.cheap_operation.1.weight", "features.14.cheap_operation.1.bias", "features.14.cheap_operation.1.running_mean", "features.14.cheap_operation.1.running_var", "features.15.weight", "features.15.bias", "features.15.running_mean", "features.15.running_var", "features.17.primary_conv.0.weight", "features.17.primary_conv.1.weight", "features.17.primary_conv.1.bias", "features.17.primary_conv.1.running_mean", "features.17.primary_conv.1.running_var", "features.17.cheap_operation.0.weight", "features.17.cheap_operation.1.weight", "features.17.cheap_operation.1.bias", "features.17.cheap_operation.1.running_mean", "features.17.cheap_operation.1.running_var", "features.18.weight", "features.18.bias", "features.18.running_mean", "features.18.running_var", "features.20.primary_conv.0.weight", "features.20.primary_conv.1.weight", "features.20.primary_conv.1.bias", "features.20.primary_conv.1.running_mean", "features.20.primary_conv.1.running_var", "features.20.cheap_operation.0.weight", "features.20.cheap_operation.1.weight", "features.20.cheap_operation.1.bias", "features.20.cheap_operation.1.running_mean", "features.20.cheap_operation.1.running_var", "features.21.weight", "features.21.bias", "features.21.running_mean", "features.21.running_var", "features.24.primary_conv.0.weight", "features.24.primary_conv.1.weight", "features.24.primary_conv.1.bias", "features.24.primary_conv.1.running_mean", "features.24.primary_conv.1.running_var", "features.24.cheap_operation.0.weight", "features.24.cheap_operation.1.weight", "features.24.cheap_operation.1.bias", "features.24.cheap_operation.1.running_mean", "features.24.cheap_operation.1.running_var", "features.25.weight", "features.25.bias", "features.25.running_mean", "features.25.running_var", "features.27.primary_conv.0.weight", "features.27.primary_conv.1.weight", "features.27.primary_conv.1.bias", "features.27.primary_conv.1.running_mean", "features.27.primary_conv.1.running_var", "features.27.cheap_operation.0.weight", "features.27.cheap_operation.1.weight", "features.27.cheap_operation.1.bias", "features.27.cheap_operation.1.running_mean", "features.27.cheap_operation.1.running_var", "features.28.weight", "features.28.bias", "features.28.running_mean", "features.28.running_var", "features.30.primary_conv.0.weight", "features.30.primary_conv.1.weight", "features.30.primary_conv.1.bias", "features.30.primary_conv.1.running_mean", "features.30.primary_conv.1.running_var", "features.30.cheap_operation.0.weight", "features.30.cheap_operation.1.weight", "features.30.cheap_operation.1.bias", "features.30.cheap_operation.1.running_mean", "features.30.cheap_operation.1.running_var", "features.31.weight", "features.31.bias", "features.31.running_mean", "features.31.running_var", "features.34.primary_conv.0.weight", "features.34.primary_conv.1.weight", "features.34.primary_conv.1.bias", "features.34.primary_conv.1.running_mean", "features.34.primary_conv.1.running_var", "features.34.cheap_operation.0.weight", "features.34.cheap_operation.1.weight", "features.34.cheap_operation.1.bias", "features.34.cheap_operation.1.running_mean", "features.34.cheap_operation.1.running_var", "features.35.weight", "features.35.bias", "features.35.running_mean", "features.35.running_var", "features.37.primary_conv.0.weight", "features.37.primary_conv.1.weight", "features.37.primary_conv.1.bias", "features.37.primary_conv.1.running_mean", "features.37.primary_conv.1.running_var", "features.37.cheap_operation.0.weight", "features.37.cheap_operation.1.weight", "features.37.cheap_operation.1.bias", "features.37.cheap_operation.1.running_mean", "features.37.cheap_operation.1.running_var", "features.38.weight", "features.38.bias", "features.38.running_mean", "features.38.running_var", "features.40.primary_conv.0.weight", "features.40.primary_conv.1.weight", "features.40.primary_conv.1.bias", "features.40.primary_conv.1.running_mean", "features.40.primary_conv.1.running_var", "features.40.cheap_operation.0.weight", "features.40.cheap_operation.1.weight", "features.40.cheap_operation.1.bias", "features.40.cheap_operation.1.running_mean", "features.40.cheap_operation.1.running_var", "features.41.weight", "features.41.bias", "features.41.running_mean", "features.41.running_var", "classifier.weight", "classifier.bias". 
        Unexpected key(s) in state_dict: "". 

执行python bin/04\_fmap\_vis.py 生成时间戳的events.out文件报错
在04_fmap_vis.py文件中的路径已经改成自己最新训练保存的pkl文件
path_checkpoint = os.path.join(BASE_DIR, "..", "results", "09-24_11-11", "checkpoint_best.pkl")

**Comment by TingsongYu** [comment]
这是模型参数字典的Key对不上，检查你的.pkl文件加载进来的字典为什么是那些key
