### ISSUE TITLE
ModuleNotFoundError: No module named 'models.ghost_net'

### ISSUE THREAD

**Issue by dreamitpossible1** [TingsongYu/ghostnet_cifar10#6]
运行python bin/02_main.py -gpu 1 0 -arc vgg16 -replace_conv进行训练提示：Traceback (most recent call last): File "bin/02_main.py", line 17, in <module> from models.ghost_net import GhostModule ModuleNotFoundError: No module named 'models.ghost_net'， 在models文件夹里面存在ghost_net，这是什么原因呢？

**Comment by TingsongYu** [comment]
添加相应路径到环境变量当中，sys.path.append(你的包所在的目录)
具体可看：https://www.itdaan.com/blog/2017/05/04/9bcb827705ea999c44b5fc5eca2b20e6.html



在 2020-10-13 11:34:45，"dreamitpossible1" <notifications@github.com> 写道：

运行python bin/02_main.py -gpu 1 0 -arc vgg16 -replace_conv进行训练提示：Traceback (most recent call last): File "bin/02_main.py", line 17, in from models.ghost_net import GhostModule ModuleNotFoundError: No module named 'models.ghost_net'， 在models文件夹里面存在ghost_net，这是什么原因呢？

**Comment by dreamitpossible1** [comment]
谢谢大哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TingsongYu"<notifications@github.com&gt;; 
发送时间: 2020年10月13日(星期二) 下午3:35
收件人: "TingsongYu/ghostnet_cifar10"<ghostnet_cifar10@noreply.github.com&gt;; 
抄送: "鮗ぶ鮕ぢ~ .."<912589683@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TingsongYu/ghostnet_cifar10] ModuleNotFoundError: No module named &#39;models.ghost_net&#39; (#6)





 添加相应路径到环境变量当中，sys.path.append(你的包所在的目录)
 具体可看：https://www.itdaan.com/blog/2017/05/04/9bcb827705ea999c44b5fc5eca2b20e6.html
 
 
 
 在 2020-10-13 11:34:45，"dreamitpossible1" <notifications@github.com&gt; 写道：
 
 运行python bin/02_main.py -gpu 1 0 -arc vgg16 -replace_conv进行训练提示：Traceback (most recent call last): File "bin/02_main.py", line 17, in from models.ghost_net import GhostModule ModuleNotFoundError: No module named 'models.ghost_net'， 在models文件夹里面存在ghost_net，这是什么原因呢？
